USE aula1exer2;

DROP TABLE VENDA;
DROP TABLE PRODUTO;
DROP TABLE GERENTE;
DROP TABLE EMPREGADO;
DROP TABLE PESSOA;
DROP TABLE ENDERECO;
DROP TABLE TELEFONE;


DROP USER pedroHelias;
DROP USER heliasCarlos;

DROP ROLE EMPREGADO;
DROP ROLE GERENTE;